version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Running Hello World App"
      - python app.py

artifacts:
  files:
    - '**/*'